CLASS LHC_ZZCIR_CIT_DB_STU_ADMB25 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitDbStuAdmb25
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_DB_STU_ADMB25 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
